# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Configuration.proto

require 'google/protobuf'


descriptor_data = "\n\x13\x43onfiguration.proto\"l\n\rConfiguration\x12\x11\n\tserver_id\x18\x01 \x01(\x05\x12\x17\n\x0fmax_subscribers\x18\x02 \x01(\x05\x12\x16\n\x0e\x65nable_logging\x18\x03 \x01(\x08\x12\x17\n\x0f\x61llowed_domains\x18\x04 \x03(\tb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

Configuration = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Configuration").msgclass
