# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Subscriber.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'Subscriber.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10Subscriber.proto\"\x91\x01\n\nSubscriber\x12\"\n\x06status\x18\x01 \x01(\x0e\x32\x12.Subscriber.Status\x12\x14\n\x0cname_surname\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\x05\x12\x15\n\rlast_accessed\x18\x04 \x01(\x03\"&\n\x06Status\x12\x08\n\x04SUBS\x10\x00\x12\x08\n\x04ONLN\x10\x01\x12\x08\n\x04OFFL\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Subscriber_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUBSCRIBER']._serialized_start=21
  _globals['_SUBSCRIBER']._serialized_end=166
  _globals['_SUBSCRIBER_STATUS']._serialized_start=128
  _globals['_SUBSCRIBER_STATUS']._serialized_end=166
# @@protoc_insertion_point(module_scope)
