// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Capacity.proto
// Protobuf Java Version: 4.29.3

public final class Capacity {
  private Capacity() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      Capacity.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ConfigurationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Configuration)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 server_id = 1;</code>
     * @return The serverId.
     */
    int getServerId();

    /**
     * <code>int32 max_subscribers = 2;</code>
     * @return The maxSubscribers.
     */
    int getMaxSubscribers();

    /**
     * <pre>
     * repeated string allowed_domains = 4;
     * </pre>
     *
     * <code>bool enable_logging = 3;</code>
     * @return The enableLogging.
     */
    boolean getEnableLogging();
  }
  /**
   * Protobuf type {@code Configuration}
   */
  public static final class Configuration extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Configuration)
      ConfigurationOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        Configuration.class.getName());
    }
    // Use Configuration.newBuilder() to construct.
    private Configuration(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Configuration() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Capacity.internal_static_Configuration_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Capacity.internal_static_Configuration_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Capacity.Configuration.class, Capacity.Configuration.Builder.class);
    }

    public static final int SERVER_ID_FIELD_NUMBER = 1;
    private int serverId_ = 0;
    /**
     * <code>int32 server_id = 1;</code>
     * @return The serverId.
     */
    @java.lang.Override
    public int getServerId() {
      return serverId_;
    }

    public static final int MAX_SUBSCRIBERS_FIELD_NUMBER = 2;
    private int maxSubscribers_ = 0;
    /**
     * <code>int32 max_subscribers = 2;</code>
     * @return The maxSubscribers.
     */
    @java.lang.Override
    public int getMaxSubscribers() {
      return maxSubscribers_;
    }

    public static final int ENABLE_LOGGING_FIELD_NUMBER = 3;
    private boolean enableLogging_ = false;
    /**
     * <pre>
     * repeated string allowed_domains = 4;
     * </pre>
     *
     * <code>bool enable_logging = 3;</code>
     * @return The enableLogging.
     */
    @java.lang.Override
    public boolean getEnableLogging() {
      return enableLogging_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (serverId_ != 0) {
        output.writeInt32(1, serverId_);
      }
      if (maxSubscribers_ != 0) {
        output.writeInt32(2, maxSubscribers_);
      }
      if (enableLogging_ != false) {
        output.writeBool(3, enableLogging_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (serverId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, serverId_);
      }
      if (maxSubscribers_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, maxSubscribers_);
      }
      if (enableLogging_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, enableLogging_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Capacity.Configuration)) {
        return super.equals(obj);
      }
      Capacity.Configuration other = (Capacity.Configuration) obj;

      if (getServerId()
          != other.getServerId()) return false;
      if (getMaxSubscribers()
          != other.getMaxSubscribers()) return false;
      if (getEnableLogging()
          != other.getEnableLogging()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SERVER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getServerId();
      hash = (37 * hash) + MAX_SUBSCRIBERS_FIELD_NUMBER;
      hash = (53 * hash) + getMaxSubscribers();
      hash = (37 * hash) + ENABLE_LOGGING_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getEnableLogging());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Capacity.Configuration parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Capacity.Configuration parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Capacity.Configuration parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Capacity.Configuration parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Capacity.Configuration parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Capacity.Configuration parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Capacity.Configuration parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static Capacity.Configuration parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Capacity.Configuration parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static Capacity.Configuration parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Capacity.Configuration parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static Capacity.Configuration parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Capacity.Configuration prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Configuration}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Configuration)
        Capacity.ConfigurationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Capacity.internal_static_Configuration_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Capacity.internal_static_Configuration_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Capacity.Configuration.class, Capacity.Configuration.Builder.class);
      }

      // Construct using Capacity.Configuration.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        serverId_ = 0;
        maxSubscribers_ = 0;
        enableLogging_ = false;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Capacity.internal_static_Configuration_descriptor;
      }

      @java.lang.Override
      public Capacity.Configuration getDefaultInstanceForType() {
        return Capacity.Configuration.getDefaultInstance();
      }

      @java.lang.Override
      public Capacity.Configuration build() {
        Capacity.Configuration result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Capacity.Configuration buildPartial() {
        Capacity.Configuration result = new Capacity.Configuration(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(Capacity.Configuration result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.serverId_ = serverId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.maxSubscribers_ = maxSubscribers_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.enableLogging_ = enableLogging_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Capacity.Configuration) {
          return mergeFrom((Capacity.Configuration)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Capacity.Configuration other) {
        if (other == Capacity.Configuration.getDefaultInstance()) return this;
        if (other.getServerId() != 0) {
          setServerId(other.getServerId());
        }
        if (other.getMaxSubscribers() != 0) {
          setMaxSubscribers(other.getMaxSubscribers());
        }
        if (other.getEnableLogging() != false) {
          setEnableLogging(other.getEnableLogging());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                serverId_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                maxSubscribers_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                enableLogging_ = input.readBool();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int serverId_ ;
      /**
       * <code>int32 server_id = 1;</code>
       * @return The serverId.
       */
      @java.lang.Override
      public int getServerId() {
        return serverId_;
      }
      /**
       * <code>int32 server_id = 1;</code>
       * @param value The serverId to set.
       * @return This builder for chaining.
       */
      public Builder setServerId(int value) {

        serverId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 server_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearServerId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        serverId_ = 0;
        onChanged();
        return this;
      }

      private int maxSubscribers_ ;
      /**
       * <code>int32 max_subscribers = 2;</code>
       * @return The maxSubscribers.
       */
      @java.lang.Override
      public int getMaxSubscribers() {
        return maxSubscribers_;
      }
      /**
       * <code>int32 max_subscribers = 2;</code>
       * @param value The maxSubscribers to set.
       * @return This builder for chaining.
       */
      public Builder setMaxSubscribers(int value) {

        maxSubscribers_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 max_subscribers = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMaxSubscribers() {
        bitField0_ = (bitField0_ & ~0x00000002);
        maxSubscribers_ = 0;
        onChanged();
        return this;
      }

      private boolean enableLogging_ ;
      /**
       * <pre>
       * repeated string allowed_domains = 4;
       * </pre>
       *
       * <code>bool enable_logging = 3;</code>
       * @return The enableLogging.
       */
      @java.lang.Override
      public boolean getEnableLogging() {
        return enableLogging_;
      }
      /**
       * <pre>
       * repeated string allowed_domains = 4;
       * </pre>
       *
       * <code>bool enable_logging = 3;</code>
       * @param value The enableLogging to set.
       * @return This builder for chaining.
       */
      public Builder setEnableLogging(boolean value) {

        enableLogging_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * repeated string allowed_domains = 4;
       * </pre>
       *
       * <code>bool enable_logging = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearEnableLogging() {
        bitField0_ = (bitField0_ & ~0x00000004);
        enableLogging_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Configuration)
    }

    // @@protoc_insertion_point(class_scope:Configuration)
    private static final Capacity.Configuration DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Capacity.Configuration();
    }

    public static Capacity.Configuration getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Configuration>
        PARSER = new com.google.protobuf.AbstractParser<Configuration>() {
      @java.lang.Override
      public Configuration parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Configuration> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Configuration> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Capacity.Configuration getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Configuration_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Configuration_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Capacity.proto\"S\n\rConfiguration\022\021\n\tser" +
      "ver_id\030\001 \001(\005\022\027\n\017max_subscribers\030\002 \001(\005\022\026\n" +
      "\016enable_logging\030\003 \001(\010b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Configuration_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Configuration_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Configuration_descriptor,
        new java.lang.String[] { "ServerId", "MaxSubscribers", "EnableLogging", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
