// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Subscriber.proto
// Protobuf Java Version: 4.29.3

public final class SubscriberOuterClass {
  private SubscriberOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      SubscriberOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SubscriberOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Subscriber)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.Subscriber.Status status = 1;</code>
     * @return The enum numeric value on the wire for status.
     */
    int getStatusValue();
    /**
     * <code>.Subscriber.Status status = 1;</code>
     * @return The status.
     */
    SubscriberOuterClass.Subscriber.Status getStatus();

    /**
     * <code>string name_surname = 2;</code>
     * @return The nameSurname.
     */
    java.lang.String getNameSurname();
    /**
     * <code>string name_surname = 2;</code>
     * @return The bytes for nameSurname.
     */
    com.google.protobuf.ByteString
        getNameSurnameBytes();

    /**
     * <code>int32 id = 3;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>int64 last_accessed = 4;</code>
     * @return The lastAccessed.
     */
    long getLastAccessed();
  }
  /**
   * Protobuf type {@code Subscriber}
   */
  public static final class Subscriber extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Subscriber)
      SubscriberOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        Subscriber.class.getName());
    }
    // Use Subscriber.newBuilder() to construct.
    private Subscriber(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Subscriber() {
      status_ = 0;
      nameSurname_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SubscriberOuterClass.internal_static_Subscriber_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SubscriberOuterClass.internal_static_Subscriber_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SubscriberOuterClass.Subscriber.class, SubscriberOuterClass.Subscriber.Builder.class);
    }

    /**
     * Protobuf enum {@code Subscriber.Status}
     */
    public enum Status
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       * Subscribed
       * </pre>
       *
       * <code>SUBS = 0;</code>
       */
      SUBS(0),
      /**
       * <pre>
       * Online
       * </pre>
       *
       * <code>ONLN = 1;</code>
       */
      ONLN(1),
      /**
       * <pre>
       * Offline
       * </pre>
       *
       * <code>OFFL = 2;</code>
       */
      OFFL(2),
      UNRECOGNIZED(-1),
      ;

      static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
          com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
          /* major= */ 4,
          /* minor= */ 29,
          /* patch= */ 3,
          /* suffix= */ "",
          Status.class.getName());
      }
      /**
       * <pre>
       * Subscribed
       * </pre>
       *
       * <code>SUBS = 0;</code>
       */
      public static final int SUBS_VALUE = 0;
      /**
       * <pre>
       * Online
       * </pre>
       *
       * <code>ONLN = 1;</code>
       */
      public static final int ONLN_VALUE = 1;
      /**
       * <pre>
       * Offline
       * </pre>
       *
       * <code>OFFL = 2;</code>
       */
      public static final int OFFL_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Status valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Status forNumber(int value) {
        switch (value) {
          case 0: return SUBS;
          case 1: return ONLN;
          case 2: return OFFL;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Status>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Status> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Status>() {
              public Status findValueByNumber(int number) {
                return Status.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return SubscriberOuterClass.Subscriber.getDescriptor().getEnumTypes().get(0);
      }

      private static final Status[] VALUES = values();

      public static Status valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Status(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Subscriber.Status)
    }

    public static final int STATUS_FIELD_NUMBER = 1;
    private int status_ = 0;
    /**
     * <code>.Subscriber.Status status = 1;</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.Subscriber.Status status = 1;</code>
     * @return The status.
     */
    @java.lang.Override public SubscriberOuterClass.Subscriber.Status getStatus() {
      SubscriberOuterClass.Subscriber.Status result = SubscriberOuterClass.Subscriber.Status.forNumber(status_);
      return result == null ? SubscriberOuterClass.Subscriber.Status.UNRECOGNIZED : result;
    }

    public static final int NAME_SURNAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object nameSurname_ = "";
    /**
     * <code>string name_surname = 2;</code>
     * @return The nameSurname.
     */
    @java.lang.Override
    public java.lang.String getNameSurname() {
      java.lang.Object ref = nameSurname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nameSurname_ = s;
        return s;
      }
    }
    /**
     * <code>string name_surname = 2;</code>
     * @return The bytes for nameSurname.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameSurnameBytes() {
      java.lang.Object ref = nameSurname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nameSurname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_FIELD_NUMBER = 3;
    private int id_ = 0;
    /**
     * <code>int32 id = 3;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int LAST_ACCESSED_FIELD_NUMBER = 4;
    private long lastAccessed_ = 0L;
    /**
     * <code>int64 last_accessed = 4;</code>
     * @return The lastAccessed.
     */
    @java.lang.Override
    public long getLastAccessed() {
      return lastAccessed_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (status_ != SubscriberOuterClass.Subscriber.Status.SUBS.getNumber()) {
        output.writeEnum(1, status_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(nameSurname_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, nameSurname_);
      }
      if (id_ != 0) {
        output.writeInt32(3, id_);
      }
      if (lastAccessed_ != 0L) {
        output.writeInt64(4, lastAccessed_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (status_ != SubscriberOuterClass.Subscriber.Status.SUBS.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, status_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(nameSurname_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, nameSurname_);
      }
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, id_);
      }
      if (lastAccessed_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, lastAccessed_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SubscriberOuterClass.Subscriber)) {
        return super.equals(obj);
      }
      SubscriberOuterClass.Subscriber other = (SubscriberOuterClass.Subscriber) obj;

      if (status_ != other.status_) return false;
      if (!getNameSurname()
          .equals(other.getNameSurname())) return false;
      if (getId()
          != other.getId()) return false;
      if (getLastAccessed()
          != other.getLastAccessed()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + status_;
      hash = (37 * hash) + NAME_SURNAME_FIELD_NUMBER;
      hash = (53 * hash) + getNameSurname().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + LAST_ACCESSED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLastAccessed());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SubscriberOuterClass.Subscriber parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SubscriberOuterClass.Subscriber parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SubscriberOuterClass.Subscriber parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SubscriberOuterClass.Subscriber parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SubscriberOuterClass.Subscriber parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SubscriberOuterClass.Subscriber parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SubscriberOuterClass.Subscriber parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static SubscriberOuterClass.Subscriber parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static SubscriberOuterClass.Subscriber parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static SubscriberOuterClass.Subscriber parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SubscriberOuterClass.Subscriber parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static SubscriberOuterClass.Subscriber parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SubscriberOuterClass.Subscriber prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Subscriber}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Subscriber)
        SubscriberOuterClass.SubscriberOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SubscriberOuterClass.internal_static_Subscriber_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SubscriberOuterClass.internal_static_Subscriber_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SubscriberOuterClass.Subscriber.class, SubscriberOuterClass.Subscriber.Builder.class);
      }

      // Construct using SubscriberOuterClass.Subscriber.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        status_ = 0;
        nameSurname_ = "";
        id_ = 0;
        lastAccessed_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SubscriberOuterClass.internal_static_Subscriber_descriptor;
      }

      @java.lang.Override
      public SubscriberOuterClass.Subscriber getDefaultInstanceForType() {
        return SubscriberOuterClass.Subscriber.getDefaultInstance();
      }

      @java.lang.Override
      public SubscriberOuterClass.Subscriber build() {
        SubscriberOuterClass.Subscriber result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public SubscriberOuterClass.Subscriber buildPartial() {
        SubscriberOuterClass.Subscriber result = new SubscriberOuterClass.Subscriber(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(SubscriberOuterClass.Subscriber result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.status_ = status_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.nameSurname_ = nameSurname_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.lastAccessed_ = lastAccessed_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SubscriberOuterClass.Subscriber) {
          return mergeFrom((SubscriberOuterClass.Subscriber)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SubscriberOuterClass.Subscriber other) {
        if (other == SubscriberOuterClass.Subscriber.getDefaultInstance()) return this;
        if (other.status_ != 0) {
          setStatusValue(other.getStatusValue());
        }
        if (!other.getNameSurname().isEmpty()) {
          nameSurname_ = other.nameSurname_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.getLastAccessed() != 0L) {
          setLastAccessed(other.getLastAccessed());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                status_ = input.readEnum();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                nameSurname_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                id_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                lastAccessed_ = input.readInt64();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int status_ = 0;
      /**
       * <code>.Subscriber.Status status = 1;</code>
       * @return The enum numeric value on the wire for status.
       */
      @java.lang.Override public int getStatusValue() {
        return status_;
      }
      /**
       * <code>.Subscriber.Status status = 1;</code>
       * @param value The enum numeric value on the wire for status to set.
       * @return This builder for chaining.
       */
      public Builder setStatusValue(int value) {
        status_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.Subscriber.Status status = 1;</code>
       * @return The status.
       */
      @java.lang.Override
      public SubscriberOuterClass.Subscriber.Status getStatus() {
        SubscriberOuterClass.Subscriber.Status result = SubscriberOuterClass.Subscriber.Status.forNumber(status_);
        return result == null ? SubscriberOuterClass.Subscriber.Status.UNRECOGNIZED : result;
      }
      /**
       * <code>.Subscriber.Status status = 1;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(SubscriberOuterClass.Subscriber.Status value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.Subscriber.Status status = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object nameSurname_ = "";
      /**
       * <code>string name_surname = 2;</code>
       * @return The nameSurname.
       */
      public java.lang.String getNameSurname() {
        java.lang.Object ref = nameSurname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nameSurname_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name_surname = 2;</code>
       * @return The bytes for nameSurname.
       */
      public com.google.protobuf.ByteString
          getNameSurnameBytes() {
        java.lang.Object ref = nameSurname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nameSurname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name_surname = 2;</code>
       * @param value The nameSurname to set.
       * @return This builder for chaining.
       */
      public Builder setNameSurname(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        nameSurname_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string name_surname = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearNameSurname() {
        nameSurname_ = getDefaultInstance().getNameSurname();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string name_surname = 2;</code>
       * @param value The bytes for nameSurname to set.
       * @return This builder for chaining.
       */
      public Builder setNameSurnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        nameSurname_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 3;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 3;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {

        id_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        id_ = 0;
        onChanged();
        return this;
      }

      private long lastAccessed_ ;
      /**
       * <code>int64 last_accessed = 4;</code>
       * @return The lastAccessed.
       */
      @java.lang.Override
      public long getLastAccessed() {
        return lastAccessed_;
      }
      /**
       * <code>int64 last_accessed = 4;</code>
       * @param value The lastAccessed to set.
       * @return This builder for chaining.
       */
      public Builder setLastAccessed(long value) {

        lastAccessed_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>int64 last_accessed = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastAccessed() {
        bitField0_ = (bitField0_ & ~0x00000008);
        lastAccessed_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Subscriber)
    }

    // @@protoc_insertion_point(class_scope:Subscriber)
    private static final SubscriberOuterClass.Subscriber DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SubscriberOuterClass.Subscriber();
    }

    public static SubscriberOuterClass.Subscriber getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Subscriber>
        PARSER = new com.google.protobuf.AbstractParser<Subscriber>() {
      @java.lang.Override
      public Subscriber parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Subscriber> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Subscriber> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public SubscriberOuterClass.Subscriber getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Subscriber_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Subscriber_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020Subscriber.proto\"\221\001\n\nSubscriber\022\"\n\006sta" +
      "tus\030\001 \001(\0162\022.Subscriber.Status\022\024\n\014name_su" +
      "rname\030\002 \001(\t\022\n\n\002id\030\003 \001(\005\022\025\n\rlast_accessed" +
      "\030\004 \001(\003\"&\n\006Status\022\010\n\004SUBS\020\000\022\010\n\004ONLN\020\001\022\010\n\004" +
      "OFFL\020\002b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Subscriber_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Subscriber_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Subscriber_descriptor,
        new java.lang.String[] { "Status", "NameSurname", "Id", "LastAccessed", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
